#!/usr/bin/env python3
"""Validate a Hermes Report V1 HTML bundle.
No external dependencies. Intended for generated static reports/handoffs.
"""
from __future__ import annotations
import argparse, json, re
from pathlib import Path

REQUIRED_TABS = ["Résumé", "Evidence", "Output", "Benchmark", "Sources", "Failures", "Next"]
REQUIRED_IDS = ["resume", "evidence", "output", "benchmark", "sources", "failures", "next"]
REQUIRED_SOURCE_KEYS = ["generated_at", "scope", "sources_consulted", "sources_failed_or_limited", "search_queries_run", "artifacts"]

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("html", type=Path)
    ap.add_argument("--source-map", type=Path)
    ap.add_argument("--min-size", type=int, default=2500)
    args = ap.parse_args()
    errors, warnings = [], []
    if not args.html.exists():
        print(f"FAIL html missing: {args.html}")
        return 2
    text = args.html.read_text(encoding="utf-8", errors="replace")
    size = args.html.stat().st_size
    if size < args.min_size:
        errors.append(f"html too small: {size} < {args.min_size}")
    for token in ["<!doctype html", "viewport", "role=\"tablist\"", "data-tab=", "class=\"section", "Generated by Hermes Report V1"]:
        if token.lower() not in text.lower():
            errors.append(f"missing html token: {token}")
    for tab in REQUIRED_TABS:
        if tab not in text:
            warnings.append(f"recommended tab label absent: {tab}")
    for ident in REQUIRED_IDS:
        if f'id="{ident}"' not in text and f"id='{ident}'" not in text:
            errors.append(f"missing section id: {ident}")
    leftovers = sorted(set(re.findall(r"\{\{[A-Z0-9_]+\}\}", text)))
    if leftovers:
        errors.append(f"unreplaced placeholders: {', '.join(leftovers[:10])}")
    if args.source_map:
        if not args.source_map.exists():
            errors.append(f"source map missing: {args.source_map}")
        else:
            try:
                sm = json.loads(args.source_map.read_text(encoding="utf-8"))
            except Exception as e:
                errors.append(f"source map invalid json: {e}")
                sm = {}
            for k in REQUIRED_SOURCE_KEYS:
                if k not in sm:
                    errors.append(f"source map missing key: {k}")
            for i, s in enumerate(sm.get("sources_consulted", []) if isinstance(sm.get("sources_consulted"), list) else []):
                for k in ["id", "title", "url", "status", "theme", "takeaway"]:
                    if k not in s:
                        errors.append(f"sources_consulted[{i}] missing {k}")
            for a in sm.get("artifacts", []) if isinstance(sm.get("artifacts"), list) else []:
                p = a.get("path")
                if p and p.startswith("/opt/data") and not Path(p).exists():
                    warnings.append(f"artifact path not found: {p}")
    print(json.dumps({"status": "fail" if errors else "pass", "html": str(args.html), "size_bytes": size, "errors": errors, "warnings": warnings}, indent=2, ensure_ascii=False))
    return 1 if errors else 0

if __name__ == "__main__":
    raise SystemExit(main())
